"""Sauce

Revision ID: 2273dc36a3f4
Revises: 786ec4e857ec
Create Date: 2025-06-24 09:50:53.471192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2273dc36a3f4'
down_revision = '786ec4e857ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('pizza_type', 'description',
     #          existing_type=sa.VARCHAR(length=100),
      #         type_=sa.String(length=30),
       #        existing_nullable=False)
    op.create_table('sauces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('spicieness', sa.Enum('mild','unmild', 'unhealthy', name='spcieness_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.add_column('pizza_type',
                  sa.Column('sauces', sa.String(), nullable=True, server_default='tomato sauces')
                  )

    #Nach der migration der alten soßen keinen default mehr
    op.alter_column('pizza_type', 'sauces', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('pizza_type', 'description',
     #          existing_type=sa.String(length=30),
      #         type_=sa.VARCHAR(length=100),
       #        existing_nullable=False)


    op.drop_table('sauces')
    sa.Enum(name='spcieness_enum').drop(op.get_bind())

    op.drop_column('pizza_type', 'sauces')

    # ### end Alembic commands ###
