"""discription_update

Revision ID: 786ec4e857ec
Revises: 40ae859bce90
Create Date: 2025-06-02 13:39:24.558548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786ec4e857ec'
down_revision = '40ae859bce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza_type', 'description',
                    existing_type=sa.String(length=30),
                    type_=sa.String(length=100),
                    existing_nullable=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('pizza_type', 'description',
                    existing_type=sa.String(length=100),
                    type_=sa.String(length=30),
                    existing_nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
